# Generated by Django 3.1.3 on 2021-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0003_python_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='python',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='python',
            name='image',
            field=models.ImageField(default=1, upload_to='media_snake_images'),
            preserve_default=False,
        ),
    ]
