# Generated by Django 3.1.3 on 2021-07-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0005_python_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='python',
            name='created_by',
        ),
    ]
